### ISSUE TITLE
Build failing when bit6 is installed

### ISSUE THREAD

**Issue by anchetaWern** [bit6/bit6-cordova#2] opened 2015-05-26 00:19 UTC
Hi, I'm trying to use bit6 to implement audio calls in the app that I'm making. But whenever its installed, the build is failing. I'm using Ionic for this project. Here's the error that I'm getting:

```
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'android'.
> Cannot evaluate module myproject-google-play-services_lib : Configuration with name 'debug' not found.

BUILD FAILED

Total time: 21.455 secs

/home/wern/www/myproject/myproject/platforms/android/cordova/node_modules/q/q.js:126
                    throw e;
                          ^
Error code 1 for command: /home/wern/www/myproject/myproject/platforms/android/gradlew with args: cdvBuildDebug,-b,/home/wern/www/myproject/chatapp/platforms/android/build.gradle,-Dorg.gradle.daemon=true
ERROR building one of the platforms: Error: /home/wern/www/myproject/myproject/platforms/android/cordova/build: Command failed with exit code 8
You may not have the required environment or OS to build this project
Error: /home/wern/www/myproject/myproject/platforms/android/cordova/build: Command failed with exit code 8
    at ChildProcess.whenDone (/home/wern/.nvm/v0.10.33/lib/node_modules/cordova/node_modules/cordova-lib/src/cordova/superspawn.js:131:23)
    at ChildProcess.emit (events.js:98:17)
    at maybeClose (child_process.js:756:16)
    at Process.ChildProcess._handle.onexit (child_process.js:823:5)
```

**Comment by narek-h** [comment] 2015-05-26 15:27
Hello, 

I'm trying to reproduce the issue using ionic, but no luck. The build goes without problem on my side. 

Could you please provide some more info that I can simulate the situation better?

.The plugin list actually installed for the project 
  (just output from  "ionic plugin list'). 

. version of cordova you are using.

. version of android build tools 

. OS 

. build system - do you use gradle or ant ? 
  It seems to be gradle right ? Just to confirm. 

  I tried both, and the build was ok. 

  Maybe you can try with ant ? 
  Env variables  'ANDROID_BUILD=ant' should do the thing. 

 I think this should be enough to continue the investigation.  Please let me know. 

  Thanks,
     Narek

**Comment by praneeth4victory** [comment] 2015-07-09 18:39
Any one has fix for this issue, Please help to fix this issue.

TIA,
Praneeth

**Comment by anchetaWern** [comment] 2015-07-13 13:54
I was able to get this to work by removing the platform and then bringing it back again:

```
cordova platform remove android
cordova platform add android
```

**Comment by narek-h** [comment] 2016-03-02 16:33
Seems the issue can be closed (not a real issue and fixed on user's side).

**Closed as completed by narek-h** 2016-03-02 16:33 UTC
